/** Public R2 bucket — LucasGuide game screenshots & guide assets */
export const R2_ASSETS_BASE =
  "https://pub-569323f832f84244a5766b065936dc37.r2.dev/LucasGuide";

export const supermarketChaosImages = {
  /** Game card, hub OG, homepage cover */
  feature: `${R2_ASSETS_BASE}/Supermarket-Chaos-Feature-LucasGuide.jpg`,
  /** Three Modes overview — use in hub / achievement Mode section */
  threeMode: `${R2_ASSETS_BASE}/Supermarket-Chaos-Three-Mode-LucasGuide.jpg`,
  stage1Start: `${R2_ASSETS_BASE}/Supermarket-Chaos-Stage-1-Start-LucasGuide.jpg`,
  skills: `${R2_ASSETS_BASE}/Supermarket-Chaos-Skills-LucasGuide.jpg`,
  rightClickThrow: `${R2_ASSETS_BASE}/Supermarket-Chaos-Right-Click-Throw-LucasGuide.jpg`,
  yellowTag: `${R2_ASSETS_BASE}/Supermarket-Chaos-Yellow-Tag-LucasGuide.jpg`,
  changeMusic: `${R2_ASSETS_BASE}/Supermarket-Chaos-Change-Music-LucasGuide.jpg`,
  atmGacha: `${R2_ASSETS_BASE}/Supermarket-Chaos-ATM-gacha-LucasGuide.jpg`,
  ending: `${R2_ASSETS_BASE}/Supermarket-Chaos-Ending-LucasGuide.jpg`,
  dreamlikeMagazines: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Magazines-LucasGuide.jpg`,
  dreamlikeElectronicsTools: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Electronics-Tools-LucasGuide.jpg`,
  dreamlikeSnacksCereal: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Snacks-Cereal-LucasGuide.jpg`,
  dreamlikeRamen: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Ramen-LucasGuide.jpg`,
  dreamlikeCleaningLaundry: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Cleaning-Laundry-LucasGuide.jpg`,
  dreamlikeHairCare: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Hair-Care-LucasGuide.jpg`,
  dreamlikeDrinks: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Drinks-LucasGuide.jpg`,
  dreamlikeCannedDrinksAlcohol: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Canned-Drinks-Alcohol-LucasGuide.jpg`,
  dreamlikeFrozenFoodsIceCream: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Frozen-Foods-Ice-Cream-LucasGuide.jpg`,
  dreamlikeBentoOnigiriSandwiches: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Bento-Onigiri-Sandwiches-LucasGuide.jpg`,
} as const;

export const titanicEscapeSimulatorImages = {
  feature: `${R2_ASSETS_BASE}/TES-Feature-LucasGuide.jpg`,
  start: `${R2_ASSETS_BASE}/TES-Start-LucasGuide.jpg`,
  tes001: `${R2_ASSETS_BASE}/TES-001-Puzzle-033109-LucasGuide.jpg`,
  tes002: `${R2_ASSETS_BASE}/TES-002-Cable-C70-LucasGuide.jpg`,
  tes003: `${R2_ASSETS_BASE}/TES-003-Crate-404-LucasGuide.jpg`,
  tes004: `${R2_ASSETS_BASE}/TES-004-Puzzle-0404-LucasGuide.jpg`,
  tes005: `${R2_ASSETS_BASE}/TES-005-Wireless-Room-LucasGuide.jpg`,
  tes006: `${R2_ASSETS_BASE}/TES-006-Boat-Deck-LucasGuide.jpg`,
  tes007: `${R2_ASSETS_BASE}/TES-007-Turkish-Baths-LucasGuide.jpg`,
  tes008: `${R2_ASSETS_BASE}/TES-008-F-Deck-LucasGuide.jpg`,
  tes009: `${R2_ASSETS_BASE}/TES-009-Turkish-Baths-LucasGuide.jpg`,
  tes010: `${R2_ASSETS_BASE}/TES-010-Mr-Graves-LucasGuide.jpg`,
  tes015: `${R2_ASSETS_BASE}/TES-015-Escape-LucasGuide.jpg`,
  ending1: `${R2_ASSETS_BASE}/TES-Ending-1-LucasGuide.jpg`,
  ending2: `${R2_ASSETS_BASE}/TES-Ending-2-LucasGuide.jpg`,
  ending3: `${R2_ASSETS_BASE}/TES-Ending-3-LucasGuide.jpg`,
} as const;

export const welcomeToElderfieldImages = {
  feature: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Feature-LucasGuide.jpg`,
  newStartWeapon: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-New-Start-Weapon-LucasGuide.jpg`,
  extraControls: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Extra-Controls-LucasGuide.jpg`,
  skillPrecisionStrike: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Skill-Precision-Strike-LucasGuide.jpg`,
  swiftLethalDefensive: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Swift-Lethal-Defensive-LucasGuide.jpg`,
  point6Lucky: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Point-6-Lucky-LucasGuide.jpg`,
  bathtub: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Bathtub-LucasGuide.jpg`,
  bed: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Bed-LucasGuide.jpg`,
  journal: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Journal-LucasGuide.jpg`,
  tv: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-TV-LucasGuide.jpg`,
  tanner: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Tanner-LucasGuide.jpg`,
  townOutskirtsWest: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Town-Outskirts-West-LucasGuide.jpg`,
  farmerHans: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Farmer-Hans-LucasGuide.jpg`,
  farmingShop: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Farming-Shop-LucasGuide.jpg`,
  growCrops: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Grow-Crops-LucasGuide.jpg`,
  npcBoundFarmer: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Bound-Farmer-LucasGuide.jpg`,
  tannersCabin: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Tanners-Cabin-LucasGuide.jpg`,
  minesCave: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Mines-Cave-LucasGuide.jpg`,
  npcMolly: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Molly-Romance-LucasGuide.jpg`,
  mallRat: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Mall-Rat-LucasGuide.jpg`,
  enemyOfficeSlime: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Enemy-Office-Slime-A-B-L-LucasGuide.jpg`,
  enemyMallAdministrator: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Enemy-Mall-Administrator-LucasGuide.jpg`,
  map: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Map-LucasGuide.jpg`,
  taxMan: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-The-Tax-Man-LucasGuide.jpg`,
  fatherDesmond: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Father-Desmond-LucasGuide.jpg`,
  seasonOfRebirth: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Season-of-Rebirth-LucasGuide.jpg`,
  elderfieldSaloon: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Elderfield-Saloon-LucasGuide.jpg`,
  saloonShop: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Saloon-Shop-LucasGuide.jpg`,
  enemyDripper: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Enemy-Dripper-LucasGuide.jpg`,
  enemyBagBoy: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Enemy-Bag-Boy-LucasGuide.jpg`,
  enemyMaggotMan: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Maggot-Man-LucasGuide.jpg`,
  ritual: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Ritual-LucasGuide.jpg`,
  energyShot: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Energy-Shot-LucasGuide.jpg`,
  npcShopper: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Shopper-LucasGuide.jpg`,
  vendingMachine: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Vending-Machine-LucasGuide.jpg`,
  fishing: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Fishing-LucasGuide.jpg`,
  npcHerb: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Herb-LucasGuide.jpg`,
  spoiledRations: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Spoiled-Rations-LucasGuide.jpg`,
  dough: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Dough-LucasGuide.jpg`,
  npcGabby: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Gabby-LucasGuide.jpg`,
  generalStore: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-General-Store-LucasGuide.jpg`,
  basicSkeletonKey: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Basic-Skeleton-Key-LucasGuide.jpg`,
  npcAlice: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Alice-LucasGuide.jpg`,
  davesHome: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Daves-Home-LucasGuide.jpg`,
  woodenStick: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Wooden-Stick-LucasGuide.jpg`,
  npcAmelia: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Amelia-LucasGuide.jpg`,
  npcMartin: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Martin-LucasGuide.jpg`,
  oldManJackson: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Old-Man-Jackson-LucasGuide.jpg`,
  petShop: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Pet-Shop-LucasGuide.jpg`,
  npcJuan: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Juan-LucasGuide.jpg`,
  npcSam: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Sam-LucasGuide.jpg`,
  policeStation: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Police-Station-LucasGuide.jpg`,
} as const;

/** Cover — set when feature image is on R2 */
export const hiddenPortalsImages = {
  feature: undefined as string | undefined,
} as const;
