/** Public R2 bucket — LucasGuide game screenshots & guide assets */
export const R2_ASSETS_BASE =
  "https://pub-569323f832f84244a5766b065936dc37.r2.dev/LucasGuide";

export const supermarketChaosImages = {
  /** Game card, hub OG, homepage cover */
  feature: `${R2_ASSETS_BASE}/Supermarket-Chaos-Feature-LucasGuide.jpg`,
  /** Three Modes overview — use in hub / achievement Mode section */
  threeMode: `${R2_ASSETS_BASE}/Supermarket-Chaos-Three-Mode-LucasGuide.jpg`,
  stage1Start: `${R2_ASSETS_BASE}/Supermarket-Chaos-Stage-1-Start-LucasGuide.jpg`,
  skills: `${R2_ASSETS_BASE}/Supermarket-Chaos-Skills-LucasGuide.jpg`,
  rightClickThrow: `${R2_ASSETS_BASE}/Supermarket-Chaos-Right-Click-Throw-LucasGuide.jpg`,
  yellowTag: `${R2_ASSETS_BASE}/Supermarket-Chaos-Yellow-Tag-LucasGuide.jpg`,
  changeMusic: `${R2_ASSETS_BASE}/Supermarket-Chaos-Change-Music-LucasGuide.jpg`,
  atmGacha: `${R2_ASSETS_BASE}/Supermarket-Chaos-ATM-gacha-LucasGuide.jpg`,
  ending: `${R2_ASSETS_BASE}/Supermarket-Chaos-Ending-LucasGuide.jpg`,
  dreamlikeMagazines: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Magazines-LucasGuide.jpg`,
  dreamlikeElectronicsTools: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Electronics-Tools-LucasGuide.jpg`,
  dreamlikeSnacksCereal: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Snacks-Cereal-LucasGuide.jpg`,
  dreamlikeRamen: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Ramen-LucasGuide.jpg`,
  dreamlikeCleaningLaundry: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Cleaning-Laundry-LucasGuide.jpg`,
  dreamlikeHairCare: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Hair-Care-LucasGuide.jpg`,
  dreamlikeDrinks: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Drinks-LucasGuide.jpg`,
  dreamlikeCannedDrinksAlcohol: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Canned-Drinks-Alcohol-LucasGuide.jpg`,
  dreamlikeFrozenFoodsIceCream: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Frozen-Foods-Ice-Cream-LucasGuide.jpg`,
  dreamlikeBentoOnigiriSandwiches: `${R2_ASSETS_BASE}/Supermarket-Chaos-Dream-Convenience-Store-Bento-Onigiri-Sandwiches-LucasGuide.jpg`,
} as const;

export const titanicEscapeSimulatorImages = {
  feature: `${R2_ASSETS_BASE}/TES-Feature-LucasGuide.jpg`,
  start: `${R2_ASSETS_BASE}/TES-Start-LucasGuide.jpg`,
  tes001: `${R2_ASSETS_BASE}/TES-001-Puzzle-033109-LucasGuide.jpg`,
  tes002: `${R2_ASSETS_BASE}/TES-002-Cable-C70-LucasGuide.jpg`,
  tes003: `${R2_ASSETS_BASE}/TES-003-Crate-404-LucasGuide.jpg`,
  tes004: `${R2_ASSETS_BASE}/TES-004-Puzzle-0404-LucasGuide.jpg`,
  tes005: `${R2_ASSETS_BASE}/TES-005-Wireless-Room-LucasGuide.jpg`,
  tes006: `${R2_ASSETS_BASE}/TES-006-Boat-Deck-LucasGuide.jpg`,
  tes007: `${R2_ASSETS_BASE}/TES-007-Turkish-Baths-LucasGuide.jpg`,
  tes008: `${R2_ASSETS_BASE}/TES-008-F-Deck-LucasGuide.jpg`,
  tes009: `${R2_ASSETS_BASE}/TES-009-Turkish-Baths-LucasGuide.jpg`,
  tes010: `${R2_ASSETS_BASE}/TES-010-Mr-Graves-LucasGuide.jpg`,
  tes015: `${R2_ASSETS_BASE}/TES-015-Escape-LucasGuide.jpg`,
  ending1: `${R2_ASSETS_BASE}/TES-Ending-1-LucasGuide.jpg`,
  ending2: `${R2_ASSETS_BASE}/TES-Ending-2-LucasGuide.jpg`,
  ending3: `${R2_ASSETS_BASE}/TES-Ending-3-LucasGuide.jpg`,
} as const;

export const welcomeToElderfieldImages = {
  feature: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Feature-LucasGuide.jpg`,
  newStartWeapon: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-New-Start-Weapon-LucasGuide.jpg`,
  extraControls: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Extra-Controls-LucasGuide.jpg`,
  skillPrecisionStrike: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Skill-Precision-Strike-LucasGuide.jpg`,
  swiftLethalDefensive: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Swift-Lethal-Defensive-LucasGuide.jpg`,
  point6Lucky: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Point-6-Lucky-LucasGuide.jpg`,
  bathtub: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Bathtub-LucasGuide.jpg`,
  bed: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Bed-LucasGuide.jpg`,
  journal: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Journal-LucasGuide.jpg`,
  tv: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-TV-LucasGuide.jpg`,
  tanner: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Tanner-LucasGuide.jpg`,
  townOutskirtsWest: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Town-Outskirts-West-LucasGuide.jpg`,
  farmerHans: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Farmer-Hans-LucasGuide.jpg`,
  farmingShop: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Farming-Shop-LucasGuide.jpg`,
  growCrops: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Grow-Crops-LucasGuide.jpg`,
  npcBoundFarmer: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Bound-Farmer-LucasGuide.jpg`,
  tannersCabin: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Tanners-Cabin-LucasGuide.jpg`,
  minesCave: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Mines-Cave-LucasGuide.jpg`,
  npcMolly: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Molly-Romance-LucasGuide.jpg`,
  mallRat: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Mall-Rat-LucasGuide.jpg`,
  enemyOfficeSlime: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Enemy-Office-Slime-A-B-L-LucasGuide.jpg`,
  enemyMallAdministrator: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Enemy-Mall-Administrator-LucasGuide.jpg`,
  map: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Map-LucasGuide.jpg`,
  mapNpcLabeled: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Map-NPC-Labled-LucasGuide.jpg`,
  taxMan: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-The-Tax-Man-LucasGuide.jpg`,
  fatherDesmond: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Father-Desmond-LucasGuide.jpg`,
  seasonOfRebirth: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Season-of-Rebirth-LucasGuide.jpg`,
  elderfieldSaloon: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Elderfield-Saloon-LucasGuide.jpg`,
  saloonShop: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Saloon-Shop-LucasGuide.jpg`,
  enemyDripper: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Enemy-Dripper-LucasGuide.jpg`,
  enemyBagBoy: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Enemy-Bag-Boy-LucasGuide.jpg`,
  enemyMaggotMan: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Maggot-Man-LucasGuide.jpg`,
  ritual: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Ritual-LucasGuide.jpg`,
  energyShot: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Energy-Shot-LucasGuide.jpg`,
  npcShopper: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Shopper-LucasGuide.jpg`,
  vendingMachine: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Vending-Machine-LucasGuide.jpg`,
  fishing: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Fishing-LucasGuide.jpg`,
  npcHerb: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Herb-LucasGuide.jpg`,
  spoiledRations: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Spoiled-Rations-LucasGuide.jpg`,
  dough: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Dough-LucasGuide.jpg`,
  npcGabby: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Gabby-LucasGuide.jpg`,
  generalStore: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-General-Store-LucasGuide.jpg`,
  basicSkeletonKey: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Basic-Skeleton-Key-LucasGuide.jpg`,
  npcAlice: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Alice-LucasGuide.jpg`,
  davesHome: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Daves-Home-LucasGuide.jpg`,
  woodenStick: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Wooden-Stick-LucasGuide.jpg`,
  npcAmelia: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Amelia-LucasGuide.jpg`,
  npcMartin: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Martin-LucasGuide.jpg`,
  oldManJackson: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Old-Man-Jackson-LucasGuide.jpg`,
  petShop: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Pet-Shop-LucasGuide.jpg`,
  npcJuan: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Juan-LucasGuide.jpg`,
  npcSam: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-NPC-Sam-LucasGuide.jpg`,
  policeStation: `${R2_ASSETS_BASE}/Welcome-to-Elderfield-Police-Station-LucasGuide.jpg`,
} as const;

export const animalyBarNoHumanityImages = {
  feature: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Feature-LucasGuide.jpg`,
  startIntro: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Start-Intro-LucasGuide.jpg`,
  buyOrangeJuice: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Buy-Orange-Juice-LucasGuide.jpg`,
  recipes: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Recipes-LucasGuide.jpg`,
  agentPengu: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Agent-Pengu-LucasGuide.jpg`,
  suspicionCriteria: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Suspicion-Criteria-LucasGuide.jpg`,
  press1GunShoot: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Press-1-Gun-Shoot-LucasGuide.jpg`,
  panda: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Panda-LucasGuide.jpg`,
  cat: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Cat-LucasGuide.jpg`,
  turtle: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Turtle-LucasGuide.jpg`,
  bull: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Bull-LucasGuide.jpg`,
  owl: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Owl-LucasGuide.jpg`,
  elephant: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Elephant-LucasGuide.jpg`,
  bearBadNews: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Bear-Bad-News-LucasGuide.jpg`,
  crocodilePoorBeer: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Crocodile-Poor-Beer-LucasGuide.jpg`,
  giraffe: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Giraffe-LucasGuide.jpg`,
  hamster: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Hamster-LucasGuide.jpg`,
  pig: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Pig-LucasGuide.jpg`,
  pigeon: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Pigeon-LucasGuide.jpg`,
  rhino: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Rhino-LucasGuide.jpg`,
  tiger: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Tiger-LucasGuide.jpg`,
  whoBathroom: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Who-Bathroom-LucasGuide.jpg`,
  itsMyFather: `${R2_ASSETS_BASE}/Animaly-Bar-No-Humanity-Its-My-Father-LucasGuide.jpg`,
} as const;

export const twentyMoreMazesImages = {
  feature: `${R2_ASSETS_BASE}/20-More-Somehow-Even-Smaller-Mazes-Feature-LucasGuide.jpg`,
  threeDigits7: `${R2_ASSETS_BASE}/20-More-Somehow-Even-Smaller-Mazes-3-Digits-Puzzles-7-LucasGuide.jpg`,
  movingDots4: `${R2_ASSETS_BASE}/20-More-Somehow-Even-Smaller-Mazes-Moving-Dots-Puzzles-4-LucasGuide.jpg`,
  blocks8: `${R2_ASSETS_BASE}/20-More-Somehow-Even-Smaller-Mazes-Blocks-Puzzles-8-LucasGuide.jpg`,
  pacmanSnake9: `${R2_ASSETS_BASE}/20-More-Somehow-Even-Smaller-Mazes-Pacman-Snake-Puzzles-9-LucasGuide.jpg`,
  connectDots17: `${R2_ASSETS_BASE}/20-More-Somehow-Even-Smaller-Mazes-Connect-the-Dot-Puzzles-17-LucasGuide.jpg`,
  endingAchievement: `${R2_ASSETS_BASE}/20-More-Somehow-Even-Smaller-Mazes-An-Ending-Achievement-LucasGuide.jpg`,
} as const;

export const monsterAlchemyImages = {
  feature: `${R2_ASSETS_BASE}/Monster-Alchemy-Feature-LucasGuide.jpg`,
  alchemistTower: `${R2_ASSETS_BASE}/Monster-Alchemy-Alchemist-Tower-LucasGuide.jpg`,
  assignedMonsters: `${R2_ASSETS_BASE}/Monster-Alchemy-Assigned-Monsters-LucasGuide.jpg`,
  baLhaBridgeMap: `${R2_ASSETS_BASE}/Monster-Alchemy-Ba-lha-Bridge-Map-Location-LucasGuide.jpg`,
  basicAttack: `${R2_ASSETS_BASE}/Monster-Alchemy-Basic-Attack-LucasGuide.jpg`,
  bossVampireAdept: `${R2_ASSETS_BASE}/Monster-Alchemy-Boss-Vampire-Adept-LucasGuide.jpg`,
  chimericChamber: `${R2_ASSETS_BASE}/Monster-Alchemy-Chimeric-Chamber-LucasGuide.jpg`,
  createMonsters: `${R2_ASSETS_BASE}/Monster-Alchemy-Create-Monsters-LucasGuide.jpg`,
  dashtPlateauTowerMap: `${R2_ASSETS_BASE}/Monster-Alchemy-Dasht-Plateau-Alchemist-Tower-Map-Location-LucasGuide.jpg`,
  marloTownTowerMap: `${R2_ASSETS_BASE}/Monster-Alchemy-Marlo-Town-Alchemist-Tower-Map-Location-LucasGuide.jpg`,
  mausoleumF1: `${R2_ASSETS_BASE}/Monster-Alchemy-Mausoleum-Dungeon-F1-LucasGuide.jpg`,
  mausoleumF2: `${R2_ASSETS_BASE}/Monster-Alchemy-Mausoleum-Dungeon-F2-LucasGuide.jpg`,
  mausoleumF3: `${R2_ASSETS_BASE}/Monster-Alchemy-Mausoleum-Dungeon-F3-LucasGuide.jpg`,
  mausoleumF3Key: `${R2_ASSETS_BASE}/Monster-Alchemy-Mausoleum-Dungeon-F3-Key-Location-LucasGuide.jpg`,
  mausoleumF4: `${R2_ASSETS_BASE}/Monster-Alchemy-Mausoleum-Dungeon-F4-Location-LucasGuide.jpg`,
  mausoleumF5: `${R2_ASSETS_BASE}/Monster-Alchemy-Mausoleum-Dungeon-F5-Location-LucasGuide.jpg`,
  monsterManager: `${R2_ASSETS_BASE}/Monster-Alchemy-Monster-Manager-LucasGuide.jpg`,
  pondVillageTowerMap: `${R2_ASSETS_BASE}/Monster-Alchemy-Pond-Village-Alchemist-Tower-Map-Location-LucasGuide.jpg`,
  questFindAlchemist: `${R2_ASSETS_BASE}/Monster-Alchemy-Quest-Find-the-Alchemist-LucasGuide.jpg`,
  questRecoverArtifact: `${R2_ASSETS_BASE}/Monster-Alchemy-Quest-Recover-the-Artifact-LucasGuide.jpg`,
  questStrangeIdea: `${R2_ASSETS_BASE}/Monster-Alchemy-Quest-Strange-Idea-LucasGuide.jpg`,
  circleOfNecromancy: `${R2_ASSETS_BASE}/Monster-Alchemy-Recipe-Circle-of-Necromancy-LucasGuide.jpg`,
  skeletonServant: `${R2_ASSETS_BASE}/Monster-Alchemy-Recipe-Skeleton-Servant-LucasGuide.jpg`,
  recipesMenu: `${R2_ASSETS_BASE}/Monster-Alchemy-Recipes-Menu-LucasGuide.jpg`,
  shop: `${R2_ASSETS_BASE}/Monster-Alchemy-Shop-LucasGuide.jpg`,
  startMenu: `${R2_ASSETS_BASE}/Monster-Alchemy-Start-Menu-LucasGuide.jpg`,
  startMonsterChoosing: `${R2_ASSETS_BASE}/Monster-Alchemy-Start-Moonster-Choosing-LucasGuide.jpg`,
  sythelTowerMap: `${R2_ASSETS_BASE}/Monster-Alchemy-Sythel-Alchemist-Tower-Map-Location-LucasGuide.jpg`,
  towerManager: `${R2_ASSETS_BASE}/Monster-Alchemy-Tower-Manager-LucasGuide.jpg`,
  uncannyValleyTowerMap: `${R2_ASSETS_BASE}/Monster-Alchemy-Uncanny-Valley-Alchemist-Tower-Map-Location-LucasGuide.jpg`,
} as const;

/** Cover — set when feature image is on R2 */
export const hiddenPortalsImages = {
  feature: undefined as string | undefined,
} as const;
